name: DCO Check

on:
  pull_request:
    branches:
      - main

jobs:
  dco:
    name: DCO compliance
    runs-on: ubuntu-latest
    steps:
      # do not run on tags
      - name: Skip for tags
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: exit 0

      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Run dco-check
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: christophebedard/dco-check@0.5.0
        with:
          python-version: "3.13"
          args: "--verbose"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
